// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate_swagger = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "gabriel.adrian.felipe@gmail.com"
        },
        "license": {
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/topsecret": {
            "post": {
                "description": "Valida posicion de nave en base a array de satelites",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Valida posicion de nave",
                "parameters": [
                    {
                        "description": "Save Satellite Data",
                        "name": "satelliteData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/spaceModels.Satellites"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helpers.ReponseTopsecretFormat"
                        }
                    }
                }
            }
        },
        "/topsecret_split": {
            "get": {
                "description": "Valida posicion de nave en base a cache",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Valida posicion de nave",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helpers.ReponseTopsecretFormat"
                        }
                    }
                }
            },
            "post": {
                "description": "Guarda en cache datos por cada satelite",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Guarda en cache datos por cada satelite",
                "parameters": [
                    {
                        "description": "Save Satellite Data",
                        "name": "satelliteData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/spaceModels.Satellite"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        }
    },
    "definitions": {
        "helpers.ReponsePositionFormat": {
            "type": "object",
            "properties": {
                "x": {
                    "type": "number"
                },
                "y": {
                    "type": "number"
                }
            }
        },
        "helpers.ReponseTopsecretFormat": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "position": {
                    "$ref": "#/definitions/helpers.ReponsePositionFormat"
                }
            }
        },
        "spaceModels.Satellite": {
            "type": "object",
            "properties": {
                "coords": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "distance": {
                    "type": "number"
                },
                "message": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "spaceModels.Satellites": {
            "type": "object",
            "properties": {
                "satellites": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/spaceModels.Satellite"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo_swagger holds exported Swagger Info so clients can modify it
var SwaggerInfo_swagger = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:4000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "MELI CHALLENGE",
	Description:      "CHALLENGE: Operacíon Fuego de Quasar",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate_swagger,
}

func init() {
	swag.Register(SwaggerInfo_swagger.InstanceName(), SwaggerInfo_swagger)
}
