basePath: /
definitions:
  helpers.ReponsePositionFormat:
    properties:
      x:
        type: number
      "y":
        type: number
    type: object
  helpers.ReponseTopsecretFormat:
    properties:
      message:
        type: string
      position:
        $ref: '#/definitions/helpers.ReponsePositionFormat'
    type: object
  spaceModels.Satellite:
    properties:
      coords:
        items:
          type: number
        type: array
      distance:
        type: number
      message:
        items:
          type: string
        type: array
      name:
        type: string
    type: object
  spaceModels.Satellites:
    properties:
      satellites:
        items:
          $ref: '#/definitions/spaceModels.Satellite'
        type: array
    type: object
host: localhost:4000
info:
  contact:
    email: gabriel.adrian.felipe@gmail.com
    name: API Support
  description: 'CHALLENGE: Operacíon Fuego de Quasar'
  license:
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: MELI CHALLENGE
  version: "1.0"
paths:
  /topsecret:
    post:
      consumes:
      - application/json
      description: Valida posicion de nave en base a array de satelites
      parameters:
      - description: Save Satellite Data
        in: body
        name: satelliteData
        required: true
        schema:
          $ref: '#/definitions/spaceModels.Satellites'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.ReponseTopsecretFormat'
      summary: Valida posicion de nave
  /topsecret_split:
    get:
      consumes:
      - application/json
      description: Valida posicion de nave en base a cache
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.ReponseTopsecretFormat'
      summary: Valida posicion de nave
    post:
      consumes:
      - application/json
      description: Guarda en cache datos por cada satelite
      parameters:
      - description: Save Satellite Data
        in: body
        name: satelliteData
        required: true
        schema:
          $ref: '#/definitions/spaceModels.Satellite'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Guarda en cache datos por cada satelite
swagger: "2.0"
